"""8th migration

Revision ID: a53d364e3ba2
Revises: 
Create Date: 2024-09-26 21:49:25.737811

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a53d364e3ba2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('password', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('patent',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('patentability_score', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('novelty',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patented', sa.Boolean(), nullable=True),
    sa.Column('printed_pub', sa.Boolean(), nullable=True),
    sa.Column('public_use', sa.Boolean(), nullable=True),
    sa.Column('on_sale', sa.Boolean(), nullable=True),
    sa.Column('publicly_available', sa.Boolean(), nullable=True),
    sa.Column('patent_app', sa.Boolean(), nullable=True),
    sa.Column('inventor_underoneyear', sa.Boolean(), nullable=True),
    sa.Column('novelty_score', sa.Float(), nullable=True),
    sa.Column('patent_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['patent_id'], ['patent.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('obviousness',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('prior_art_scope', sa.String(), nullable=False),
    sa.Column('differences', sa.String(), nullable=False),
    sa.Column('skill_level', sa.String(), nullable=False),
    sa.Column('secondary_considerations', sa.String(), nullable=True),
    sa.Column('obviousness_score', sa.Float(), nullable=True),
    sa.Column('patent_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['patent_id'], ['patent.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('prior_art',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patent_number', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('abstract', sa.Text(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('patent_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['patent_id'], ['patent.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_patent',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('patent_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['patent_id'], ['patent.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'patent_id')
    )
    op.create_table('utility',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('operability', sa.Boolean(), nullable=True),
    sa.Column('beneficial', sa.Boolean(), nullable=True),
    sa.Column('practical', sa.Boolean(), nullable=True),
    sa.Column('utility_score', sa.Float(), nullable=True),
    sa.Column('patent_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['patent_id'], ['patent.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('utility')
    op.drop_table('user_patent')
    op.drop_table('prior_art')
    op.drop_table('obviousness')
    op.drop_table('novelty')
    op.drop_table('patent')
    op.drop_table('user')
    # ### end Alembic commands ###
